services:
  - type: static
    name: file-uploader-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
      - key: VITE_APP_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html